### ISSUE TITLE
[Bug report] web3.js returns a slightly different value as the wallet balances

### ISSUE THREAD

**Issue by impelcrypto** [AstarNetwork/astar-apps#103]
**Describe the bug**
This is a low priority issue (or maybe not an issue at all).
Subscan shows the account balances as 5SDN, but the web3.js library returns a slightly different amount. 
(`await web3.eth.getBalance(address)`)

![image](https://user-images.githubusercontent.com/92044428/138144470-86b6803d-a983-4d4f-97ee-2640504808e6.png)

![image](https://user-images.githubusercontent.com/92044428/138144637-bf328c75-fcea-4280-9120-06f6cbe74e4a.png)

**Comment by andabak** [comment]
@impelcrypto is this still an issue?

**Comment by impelcrypto** [comment]
@shunsukew Thank you for asking the issue https://github.com/paritytech/frontier/issues/1022 
I see this is an expected behavior.
