### ISSUE TITLE
Propose to change the add stake and unstake dialog box

### ISSUE THREAD

**Issue by togamamora** [AstarNetwork/astar-apps#109]
1. When I click on add stake, I can see the amount of "transferrable" SDN. Since we can stake not only transferrable, but also vested and locked SDN, we need to change that to "Available SDN" " or "available SDN to stake"
![image](https://user-images.githubusercontent.com/37278708/138424777-d3c378fe-04b9-4b64-b33c-93656b15f474.png)

2. When I clicked "unstake", I can see the "Transferrable SDN". In this scenario, knowing the transferrable balance is useless. What we need to know is "Staked SDN", which will guide us on how many SDN we can unstake.
![image](https://user-images.githubusercontent.com/37278708/138425078-b95071e5-0aaa-483c-ba81-314d8fd8f381.png)

**Comment by Gunit2481** [comment]
I would suggest a feature to difference SDN already staked on dApps and SDN available to stake as well.

**Comment by impelcrypto** [comment]
This issue has been resolved.
![image](https://user-images.githubusercontent.com/92044428/166179557-b261e3d6-e393-40bb-aed8-79d721f7f1fc.png)
