### ISSUE TITLE
Add Operator's Reward in claim UI

### ISSUE THREAD

**Issue by togamamora** [AstarNetwork/astar-apps#113]
I think we need to add Operator's rewards in the claim UI so that the community knows how much are they getting. Knowing this figure may help in:

1. Making decision whether to continue to support or add more support the project. E.g, the project is doing ok but lack of fundings. If this is the case, I would add more stake. or, e.g. if the project has been getting a lot of rewards but not showing good progress, I would want to stop supporting. This helps with governance decision.

2. Some projects offer kickbacks, so it would be easy to estimate what I would get from the kickbacks.

To add:
- Operator's Claimed Reward.
- Operator's Pending Reward.

**Comment by andabak** [comment]
@togamamora is this still relevant?

**Comment by andabak** [comment]
This will be addressed in the upcoming dApp Staking v3 https://forum.astar.network/t/dapps-staking-v3-proposal/4206
