### ISSUE TITLE
Add Reward History

### ISSUE THREAD

**Issue by togamamora** [AstarNetwork/astar-apps#114]
Please add reward history on the dashboard for each dap.

![Screenshot_20211024_080539](https://user-images.githubusercontent.com/37278708/138575029-11c09c95-cad0-4011-a914-60f9d83cb91b.jpg)
It can be something I can click on the green spot and pop up will appear to show the reward history of each era.

**Comment by Kahonnohak** [comment]
Total claimed rewards for each dApps will be available to see on dApp Staking V2. Thanks!
