### ISSUE TITLE
Dapps Rating

### ISSUE THREAD

**Issue by togamamora** [AstarNetwork/astar-apps#116]
Like on Google play store, users are able to give a rating on the apps. I would like to see this on the dapps store.

Leave rating and feedbacks. Dapp operators can also interact with the feedbacks. This will.be a guide to others in making decision. It also will be a guide to the operators to take action if improvement is necessary.

**Comment by Kahonnohak** [comment]
We will have the following rankings but the review will not be included in dApp Staking V2 launch. Still having likes and reviews are reserved for the next phase.

- Top gaining dApps (Staked ASTR)
- Top performance (dApp TVL)
