### ISSUE TITLE
Where can I find a final claimed reward-amount?

### ISSUE THREAD

**Issue by johnnyji-dev** [AstarNetwork/astar-apps#1203]
Actually, Im using the subscan.io api for get claimed reward-amount.

Where can I find a final claimed reward-amount by using any other dappstaking method? or anything else?

**Comment by bobo-k2** [comment]
Check the below two calls on https://api.astar.network/, it might be helpful

<img width="1394" alt="image" src="https://github.com/AstarNetwork/astar-apps/assets/8452361/d1c70bc7-ac32-4eb8-9abf-64e1dcef0ab4">

**Comment by johnnyji-dev** [comment]
> Check the below two calls on https://api.astar.network/, it might be helpful
> 
> <img alt="image" width="1394" src="https://private-user-images.githubusercontent.com/8452361/308089539-d1c70bc7-ac32-4eb8-9abf-64e1dcef0ab4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMDUxMjAsIm5iZiI6MTcwOTEwNDgyMCwicGF0aCI6Ii84NDUyMzYxLzMwODA4OTUzOS1kMWM3MGJjNy1hYzMyLTRlYjgtOWFiZi02NGUxZGNlZjBhYjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjhUMDcyMDIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzliM2MzNGIwMjMwMWVmMDVhYWMyZTg0NWZiYTBkNjI1YzVlNzBjYTNhNjUyN2VjMTcwMTJlZGFmZTEyYzg3ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TTXRHd9q-JxlkS_lxOYYXqWm84yyrHyNkYL4eMDKrL0">

thx~ I will check that out~

**Comment by johnnyji-dev** [comment]
> Check the below two calls on https://api.astar.network/, it might be helpful
> 
> <img alt="image" width="1394" src="https://private-user-images.githubusercontent.com/8452361/308089539-d1c70bc7-ac32-4eb8-9abf-64e1dcef0ab4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTQxMzcsIm5iZiI6MTcwOTExMzgzNywicGF0aCI6Ii84NDUyMzYxLzMwODA4OTUzOS1kMWM3MGJjNy1hYzMyLTRlYjgtOWFiZi02NGUxZGNlZjBhYjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjhUMDk1MDM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmU1NzczZmY3ZTFmNzJlMDUxMTgyMmRhYWYzNmNmYTc4MDM5MDc1YThjZGM2NmRkZGY3OGM5ZTk2ZjFkZDJhMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ML3oPqCyLSkdmBkjG-cFQ1BOcH2lxE8Hhkzs5hSos0M">

BTW, on https://api.astar.network/, it calls on "https://squid.subsquid.io/dapps-staking-indexer-shibuya/graphql".
hmm... I can't get some hint for how to call the blockchain-node..

**Comment by johnnyji-dev** [comment]
I found out the actual reward on event information. thx~
