### ISSUE TITLE
[Bug report] "Estimated-Reward" on portal is

### ISSUE THREAD

**Issue by johnnyji-dev** [AstarNetwork/astar-apps#1206]
**Describe the bug**
> A clear and concise description of what the bug is.

It appears that the "Estimated-Reward" displayed on the "portal.astar.network/shibuya-testnet/assets" differs significantly from the actual "Claimed-Reward on subscan".
The currently captured image reflects the values in the "shibuya-testnet" environment, but similar observations have been made in the "astar-mainnet" environment as well.

Question: Is the "Estimated-Reward" displayed on the "portal" inclusive of future "reward" that cannot currently be claimed?

**Screenshots**
> If applicable, add screenshots to help explain your problem.

![image](https://github.com/AstarNetwork/astar-apps/assets/125259310/e37c7660-358a-4010-99f4-fb3032491cbf)

![image](https://github.com/AstarNetwork/astar-apps/assets/125259310/ca045a37-f6a9-4d6d-b999-1bac2e8ece6b)

**Comment by bobo-k2** [comment]
There was a bug where the portal was showing future rewards too. Fixed in https://github.com/AstarNetwork/astar-apps/pull/1224
