### ISSUE TITLE
[Tokenomics 2.0] Max vs. Realized Inflation Display

### ISSUE THREAD

**Issue by Dinonard** [AstarNetwork/astar-apps#1259]
By doing a few simple data fetches, it's possible to show maximum vs. realized inflation.

### 1. Identify New Cycle Start & Max Inflation

When an event from pallet `Inflation, [NewInflationConfiguration](https://astar.subscan.io/event?module=inflation&event_id=NewInflationConfiguration) is emitted, it means a new cycle has started.

A snapshot of the total issuance is taken, and reward pools for the next cycle are calculated based on inflation parameters.
To replicate this, take the block **BEFORE** this even has happened, and calculate the max possible inflation.
```Rust
first_block_in_the_cycle = <block at which event was detected>;
init_total_issuance = query.balances.totalIssuance();
max_inflation_rate = query.inflation.config.maxInflationRate();
max_inflation = init_total_issuance * max_inflation_rate;
```

<img width="1754" alt="Screenshot 2024-04-08 at 15 12 10" src="https://github.com/AstarNetwork/astar-apps/assets/3002868/fb1f5701-3d74-4065-9a10-628bae17f67a">

### 2. Plot Max Inflation Line

The assumption here is that the max inflation rate will be linearly spread over the entire cycle.
X-axis contains blocks, while Y-axis contains total issuance.

The math is fairly simple: 
```Rust
cycle_length_in_blocks = <use runtime API to read this>;

cycle_progression = (x - first_block_in_the_cycle ) / cycle_length_in_blocks; // How much cycle has progressed, always between 0 and 1.
max_inflation(x) = cycle_progression * max_inflation + init_total_issuance;
```
where `x` is the block number.

### 3. Plot Realized Inflation Line

This one is also fairly simple.

At any block within the cycle, we simply read the total issuance:
```Rust
current_block = ...;
realized_total_issuance = query.balances.totalIssuance();
```

Using this number, and knowing the values from the 1st subchapter above, we can estimate the final inflation:
```Rust
cycle_length_in_blocks = <use runtime API to read this>;
cycle_progression = (x - first_block_in_the_cycle ) / cycle_length_in_blocks; // How much cycle has progressed, always between 0 and 1.

slope = (realized_total_issuance - init_total_issuance) / (x - first_block_in_the_cycle);

realized_inflation(x) = (x - first_block_in_the_cycle) * slope + init_total_issuance;
```
where `x` is the block number.

### 4. Expected Result

![Screenshot 2024-03-12 at 16 28 33](https://github.com/AstarNetwork/astar-apps/assets/3002868/1b0a88f6-4854-4b4e-8e9e-4f63ca5c3f58)

**Comment by bobo-k2** [comment]
Resolved in https://github.com/AstarNetwork/astar-apps/pull/1289
