### ISSUE TITLE
dAppStakingV3 - Tier Thresolds Derivation

### ISSUE THREAD

**Issue by ipapandinas** [AstarNetwork/astar-apps#1367]
This [PR](https://github.com/AstarNetwork/Astar/pull/1306) will be merged soon. For additional context, a [forum post](https://forum.astar.network/t/dapps-staking-v3-proposal/4206/170) explains the motivation.

This feature introduces a storage migration from v7 to v8 for pallet dappStaking.

Here are the small breaking changes introduced on types:

#### `TierThreshold` enum is updated

- *DynamicTvlAmount* & *FixedTvlAmount* variants were deleted,
- *DynamicPercentage* & *FixedPercentage* were introduced instead.

```rs
enum TierThreshold {
    FixedPercentage { required_percentage: Perbill },
    DynamicPercentage {
        percentage: Perbill,
        minimum_required_percentage: Perbill,
    },
}
```

*Note - Example of Perbill to Percent transformation: 35_700_000 = 3.57%*

#### `TierConfig` storage value: `TiersConfiguration` type is refactored
- `number_of_slots` field is removed,
- `tier_thresholds` field type is refactored from a vector of `TierThreshold`s to a vector of `Balance`s (u128).

This simplifies tier threshold amounts parsing as now item 0 of the vector refers to tier 1's threshold, item 1 to tier 2's threshold, and so on. The total number of slots can still be compute summing all items in `slots_per_tier` vector.

**Comment by bobo-k2** [comment]
Resolved in #1376
