### ISSUE TITLE
Inform the user if the remaining staked tokens is less than the minimal amount, all will be unstaked

### ISSUE THREAD

**Issue by GuiGou12358** [AstarNetwork/astar-apps#139]
When a user unstake a share of these tokens and the remaining tokens is less than the minimal staking amount, all is unstake without warning.
https://shibuya.subscan.io/extrinsic/265490-7

Maybe it will be better to display this information in the UI.

**Comment by Kahonnohak** [comment]
Created a ticket and will be included on the dApp Staking v2 launch. Thank you!
