### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by asdfggg1** [AstarNetwork/astar-apps#142]
I have 37 transferrable SDN and 9.1k locked SDN.
But I find that i have stakable SDNs all that i have on portal-shiden-network.
It shows that i can add 9.1375k too and when i write the number of SDN, the 'Stake' button is activated.
I have not tried to add.

**Comment by hoonsubin** [comment]
Please add the title of the bug and follow this template so we can reproduce the issue. https://github.com/PlasmNetwork/astar-apps/blob/main/.github/ISSUE_TEMPLATE/bug-report.md
