### ISSUE TITLE
[Feature suggestion] Add Awesome Movie on Our Portal

### ISSUE THREAD

**Issue by SotaWatanabe** [AstarNetwork/astar-apps#159]
It must be awesome if we could add this movie on our portal so that people who attended this portal can understand Astar Network clearly

<img width="887" alt="Screenshot 2021-11-18 at 11 23 37 AM" src="https://user-images.githubusercontent.com/29359048/142483298-99fb046a-d49f-4255-86d7-7afc0ae860f7.png">

**Comment by SotaWatanabe** [comment]
You can find the file here https://www.youtube.com/watch?v=8RA90uyO-ZY and here https://drive.google.com/drive/u/0/folders/11r2KI413rIlK0y-06yLvnBNVlWvUR6In

**Comment by hoonsubin** [comment]
I'm not sire if adding a video on the balance page is a good idea...
There should be a better way to present the information about Astar network without adding too much media

**Comment by SotaWatanabe** [comment]
Since this is a video for Astar, we don't need to add this on Shiden's portal. Regarding the opinion, this should be decided after hearing users' feedback. I will ask users once it is live on Astar.

**Comment by andabak** [comment]
A lot of video content related to Astar Portal was produced in the meantime so the issue can be considered closed.
