### ISSUE TITLE
[Feature suggestion] DApp Staking UI Update

### ISSUE THREAD

**Issue by SotaWatanabe** [AstarNetwork/astar-apps#161]
**Motivation**
I would like to make our UI more professional. I strongly respect Parallel Finance's UI and UX. Our UI needs to be more professional too. 

**Suggested Solution**
<img width="910" alt="Screenshot 2021-11-19 at 4 04 35 PM" src="https://user-images.githubusercontent.com/29359048/142705902-7a2d35db-c5ac-48f1-b2a6-0f5b306ce25f.png">
Obviously, we won't copy their UI and we will make the UI by ourselves. But inspired by Parallel, I would like to have this UI format.

**Comment by fiexer** [comment]
Agree!
It has to have a more professional look. We need to improve current look:
![image](https://user-images.githubusercontent.com/36227274/142777591-262f7064-f4aa-4f7a-80d7-acecd8e08614.png)

@SotaWatanabe can our designer create some designs?

**Comment by Kahonnohak** [comment]
closed
