### ISSUE TITLE
Allow transfers between H160 and SS58 addresses of Metamask extension

### ISSUE THREAD

**Issue by bLd75** [AstarNetwork/astar-apps#163]
The objective of this enhancement is to allow users to use a single key from Metamask to interact with both WASM (via ECDSA conversion) and EVM runtimes.

Currently, the portal allows to switch between H160 and SS58/ECDSA addresses from a Metamask key, but doesn't allow transfert between both addresses.
This very expected feature would allow users to use the same Metamask key in both WASM and EVM environments, allowing them to transfert directly from a CEX to SS58/ECDSA address and then make the transfert to H160 with automatic conversion.

**1. SS58/ECDSA format**
The actual conversion of Metamask key to SS58/ECDSA is made to generic substrate address format (5), it will have to be made to Shiden/Astar format. See https://www.subscan.io/tools/ss58_transform for a reference SS58 conversion tool.

**2. Workflow for SS58 > H160**
- `Convert` H160 address to SS58/SR25519 (using method polkadotCryptoUtils.evmToAddress)
- `Call transfert `from SS58/ECDSA to SS58/SR25519

**3. Workflow for H160 > SS58**
- `Check` that the SS58/ECDSA address has a positive balance for withdraw. If not, issue a warning "your WASM balance is 0, you will not be able to withdraw funds, are you sure you still want to make this transfert?"
- `Convert` SS58/ECDSA address to H160 (using method polkadotCryptoUtils.addressToEvm)
- `Call transfert `from H160 (native) to H160 (converted from SS58/ECDSA)
- Wait for transaction to complete
- `Call Withdraw` function in precompiled Smart Contract from SS58/ECDSA

**Example**

H160 address = `0xd76bB40d855dece19de5D84a6a42a07F2B82fe72`
SS58/SR25519 address (Astar format) = `YBvpjYsdepZ9veLcaLot1miHTRGpSVtu98Fkx9EF4PLZnuH`
SS58/ECDSA address (Substrate format) = `5DHiVeeCcnk1ksFAH8QoFyhEoJLJUABHdja2oeDiqwAPTVTv`
SS58/ECDSA address (Astar format) = `XAJvwcHQ2P7yhGzmRrvHdrWtM3RSNt2ew5B3MRaiJAM3jrW`
H160 converted from SS58/ECDSA address = `0x362891f09734408c9e4a1d59ea5e04d198f5eab8`

Workflow 2
- Transfert from `XAJvwcHQ2P7yhGzmRrvHdrWtM3RSNt2ew5B3MRaiJAM3jrW` to `YBvpjYsdepZ9veLcaLot1miHTRGpSVtu98Fkx9EF4PLZnuH`

Workflow 3
- Transfert from `0xd76bB40d855dece19de5D84a6a42a07F2B82fe72` to `0x362891f09734408c9e4a1d59ea5e04d198f5eab8`
- Withdraw from `5DHiVeeCcnk1ksFAH8QoFyhEoJLJUABHdja2oeDiqwAPTVTv` with parameter `0x362891f09734408c9e4a1d59ea5e04d198f5eab8`

**Comment by hoonsubin** [comment]
reopening since this issue isn't completely solved yet
