### ISSUE TITLE
[Feature suggestion]  H160 address copied in Astar portal cannot be read by the tool to convert address H160/SS58 because case sensibility

### ISSUE THREAD

**Issue by GuiGou12358** [AstarNetwork/astar-apps#170]
The H160 address copied in the Astar portal cannot be read by the tool to convert address H160/SS58 because case sensibility.

H160 address copied via Astar portal is in lowercase: 0xf5ce .....  f3
The address convertion tools (https://polkatools.hoonkim.me/index.html) manages only the addresses in uppercase: 0xF5CE .....  F3   

Note: Address copied via Metamask is in uppercase.

Solution: 
  - Address copied in Astar Portal should be in uppercase.
  - Subrstrate EVM Address converter should not be case sensitive

**Comment by hoonsubin** [comment]
The new version of the app removed the checksum address https://hoonsubin.github.io/evm-substrate-address-converter/
