### ISSUE TITLE
EVM Withdraw - Decimal Bug

### ISSUE THREAD

**Issue by togamamora** [AstarNetwork/astar-apps#176]
1. When withdrawing from EVM. I clicked MAX with 18 decimal balance, it didn't work. No confirmation box asking me to sign tx.

2. So I tried to reduce the decimals. It worked at 14 decimals and I was left with a very small balance.

3. After that, with the very small balance left, I tried to withdraw max with 18 decimals. It worked and the evm balance is now 0.  

Some users have also reported similar issue.

This is a strange scenario.

**Comment by los183** [comment]
Im currently having this issue on SDN when im im EVM withdrawing how do i resolve or what is the temporary solution?

**Comment by togamamora** [comment]
> Im currently having this issue on SDN when im im EVM withdrawing how do i resolve or what is the temporary solution?

@los183 
Please reduce decimals as suggested. Do not click max.

**Comment by los183** [comment]
I’m not inputting any decimals

**Comment by togamamora** [comment]
Do you have gas of at least 0.0017 SDN on Polkadot.js?

**Comment by los183** [comment]
Yes I have full SDN’s

**Comment by togamamora** [comment]
Please share some screenshots and the error messages here.

**Comment by Kahonnohak** [comment]
@impelcrypto I believe this has been fixed when we stopped rounding?

**Comment by andabak** [comment]
@impelcrypto @togamamora is this still relevant?

**Comment by impelcrypto** [comment]
@togamamora Pehaps it related to [this](https://github.com/AstarNetwork/astar-apps/issues/103#event-9024708797) issue? In that case, I think we can close this issue as well.
