### ISSUE TITLE
[Feature suggestion] Adding the option "keep alive" and "transfer full balance"

### ISSUE THREAD

**Issue by Theos14123** [AstarNetwork/astar-apps#180]
**Suggested Solution**
> In order to make some transfert from the app, could you add the option "keep alive" and "transfer full balance".
That will make easier the use of the dapp and we do not need to switch between the app and Polkadot.JS

Regards
Antoine

**Comment by hoonsubin** [comment]
Please add the title for this issue

**Comment by Kahonnohak** [comment]
Created a Kaizen ticket. Thank you!
