### ISSUE TITLE
Add graph for TVL

### ISSUE THREAD

**Issue by fiexer** [AstarNetwork/astar-apps#186]
**Motivation**
 Please create a daily graph that shows the evolution of TVL on dApp staking.

**Suggested Solution**
Use a graph like on our EVM explorer:
https://blockscout.com/shiden

**Alternatives**
/

**Additional Information**
/

**Comment by impelcrypto** [comment]
Added in [this](https://github.com/AstarNetwork/astar-apps/pull/362) PR.
