### ISSUE TITLE
Cannot read properties of undefined error while registering dapp

### ISSUE THREAD

**Issue by bobo-k2** [AstarNetwork/astar-apps#193]
**Describe the bug**
> The error occurred while during dapp registration process

**To Reproduce**
1. Click "Registed dApp" button
2. Enter dApp details
3. Click "Register" button

**Expected behavior**
> The dApp should be registered and display on dashboard

**Screenshots**
![image](https://user-images.githubusercontent.com/8452361/146644560-f845bcaa-6db8-43a7-b1f4-56a5f11e5cb5.png)

![image](https://user-images.githubusercontent.com/8452361/146644437-2db4fab4-e668-465f-9216-1715483e9a0b.png)

![image](https://user-images.githubusercontent.com/8452361/146716024-ba1ded57-4b6a-4bfe-b4ab-5ec658a919f9.png)

**Comment by impelcrypto** [comment]
Hi @bobo-k2,
Is the status of this issue still ‘Open’?

**Comment by bobo-k2** [comment]
This feature changed a lot, and the issue is not reported since than so I will close it
