### ISSUE TITLE
[Feature suggestion] - UX - Balance - SDN Transferable

### ISSUE THREAD

**Issue by Theos14123** [AstarNetwork/astar-apps#197]
**Motivation**
> After using transfering some SDN to my metamask, I think some improvment could be made in order to improve the user experience when using the transfer option

**Suggested Solution**
> I suggest you to adjust the "Send to" section. At first, it wasn't that obvious how to add other network than the one from Polkadot.JS. Maybe, in order to simplify the use, it will be interesting to add a sentence such as Add the adress network desired

**Alternatives**
> Another alternative, will be to add a section following the different address with a  plus "add your network"

I hope my comment will help you

**Comment by Kahonnohak** [comment]
Created a Kaizen ticket. Thanks!
