### ISSUE TITLE
Astar Portal issue - wallet will not load

### ISSUE THREAD

**Issue by MadDog2022** [AstarNetwork/astar-apps#238]
https://portal.astar.network/#/balance/wallet will not load in Chrome

When I click on the link, it opens the wallet page but will not load - I just get a spinning wheel. How do I fix this? Thx

<img width="1198" alt="Screen Shot 2022-01-25 at 6 55 30 AM" src="https://user-images.githubusercontent.com/98399188/150980951-d3aef652-3f5d-4fca-9d07-55897a873658.png">

**Comment by hoonsubin** [comment]
Hello, thank you for reporting the issue.
Can you provide us with more information? Please show us the browser log (click f12) so we can identify the issue.
Thank you.

**Comment by MadDog2022** [comment]
Thx, is this what u need?

<img width="559" alt="Screen Shot 2022-01-25 at 8 26 55 AM" src="https://user-images.githubusercontent.com/98399188/150995456-30533db3-3d90-4656-b471-4f5d1b05abe2.png">

**Comment by MadDog2022** [comment]
or is it this?

<img width="549" alt="Screen Shot 2022-01-25 at 8 37 00 AM" src="https://user-images.githubusercontent.com/98399188/150997150-6e17fa75-025f-49c0-a2bd-1f02deb4f21e.png">

**Comment by hoonsubin** [comment]
> or is it this?
> 
> <img alt="Screen Shot 2022-01-25 at 8 37 00 AM" width="549" src="https://user-images.githubusercontent.com/98399188/150997150-6e17fa75-025f-49c0-a2bd-1f02deb4f21e.png">

This is the correct one. Looks like you're trying to connect to the local node instead of the remote endpoint.
Please try to refresh your browser and select a different network from the side menu.

**Comment by MadDog2022** [comment]
all i am doing is clicking on the portal link here https://docs.astar.network/stake2earn-festival/how-to-stake

where is a "side menu"?

**Comment by MadDog2022** [comment]
if u are talking about the JS browser extension, i switched it to plasma network but it still does not work

**Comment by MadDog2022** [comment]
it was set to polkadot relay
