### ISSUE TITLE
[Feature suggestion] History view for wallet in astar portal

### ISSUE THREAD

**Issue by mebagger** [AstarNetwork/astar-apps#246]
It would be nice to have a history view on the wallet balance screen so that you could for example see the following events with the date and time:

earnings from staking being deposited
Transfer in
Transfer out
amount and location/dapp staking
amount and location/dapp unstaking

**Comment by kuma56** [comment]
Very nice idea.
It would also be much easier to manage if we could output the data in CSV format.

**Comment by Kahonnohak** [comment]
We don't rely on third parties which means it only be possible to store the history data at the user's end. So only be possible to show the transaction history on browser bases. Still, it is good to have 'Recent transaction history' :  I have created a Kaizen ticket. Hope to deliver when we renew our transfer modals. Thank you so much for your feedback!
