### ISSUE TITLE
[Bug report] Dapps Staking stuck on Nova Wallet - Android Version

### ISSUE THREAD

**Issue by marvelet** [AstarNetwork/astar-apps#249]
**Describe the bug**
> Dapps Staking page is stuck on loading on Nova Wallet (Android Mobile), can't load any pool.

**To Reproduce**
1. Go to 'Dapps'
2. Click on 'Astar Dapp Hub' or type 'portal.astar.network'
3. Load Wallet Polkadot.js
4. Click 'Dapp Staking'

**Expected behavior**
> Dapp Staking Pool won't load, stuck in loading screen. Keep loading after waiting for like more than 5 minutes. 

**Screenshots**
> 
![9338d89c-99c4-4553-8f15-0a52f0bef81e](https://user-images.githubusercontent.com/87793956/152969308-c0628351-f911-4dbb-b60f-9c6b52a81c1b.jpg)

**Smartphone (please complete the following information)**
 - Device: Xiaomi Mi 11t Pro
 - OS: MIUI Global v12.5.3
 - Browser : Nova Wallet Dapp Browser
 - Version : Nova Wallet v2.4.0-github

**Comment by impelcrypto** [comment]
The issue has been resolved.
