### ISSUE TITLE
[Bug report] Incorrect unbonding amount displayed

### ISSUE THREAD

**Issue by Dinonard** [AstarNetwork/astar-apps#284]
**Describe the bug**

When unbonding from a contract, it is possible that incorrect unbonding amount will be displayed.

`dapps-staking` backend has defined a minimum staking amount. In case user's stake goes below this
amount, they will be completely unstaked.

```Rust
/// Minimum amount user must stake on contract.
/// User can stake less if they already have the minimum staking amount staked on that particular contract.
#[pallet::constant]
type MinimumStakingAmount: Get<BalanceOf<Self>>;
```

**To Reproduce**
1.MinimumStakingAmount = 5 SBY :heavy_check_mark: 
2. I stake on **contract  X** 6 SBY :heavy_check_mark: 
3. I unbond 3 SBY :question: 
4. Message is displayed that I unbonded 3 SBY :exclamation: 

Step 3. will actually unbond 6 SBY because 6 - 3 = 3 which is less than 5 (minimum staking amount).
Message displayed to the user should reflect this.

**Expected behavior**
Correct unbonding amount should be displayed to the user.

I'd also recommend that some sort of message is displayed to the user when
they try to unbond amount which will cause them to be fully unstaked.

**Comment by Kahonnohak** [comment]
Could you help us confirm that you still having this error please?

**Comment by bobo-k2** [comment]
The bug is still present. I will take a look
