### ISSUE TITLE
[Bug report] MaxEraStake values not considered when bonding

### ISSUE THREAD

**Issue by Dinonard** [AstarNetwork/astar-apps#288]
**Describe the bug**

There is a limited amount of staking info we can store per <staker, contract> pair.
In case we exceed this storage limit, calling `bond_and_stake` will fail.

The limit is defined as:
```Rust
/// Max number of unique `EraStake` values that can exist for a `(staker, contract)` pairing.
/// When stakers claims rewards, they will either keep the number of `EraStake` values the same or they will reduce them by one.
/// Stakers cannot add an additional `EraStake` value by calling `bond&stake` or `unbond&unstake` if they've reached the max number of values.
///
/// This ensures that history doesn't grow indefinitely - if there are too many chunks, stakers should first claim their former rewards
/// before adding additional `EraStake` values.
#[pallet::constant]
type MaxEraStakeValues: Get<u32>;
```
This limit applies to the size of the struct:
```Rust
#[derive(Encode, Decode, Clone, Default, PartialEq, Eq, RuntimeDebug, TypeInfo)]
pub struct StakerInfo<Balance: AtLeast32BitUnsigned + Copy> {
    // Size of this list would be limited by a configurable constant
    stakes: Vec<EraStake<Balance>>,
}
```

At the moment what will happen:
```
stakes = staker_info.stakes;

if stakes.length == (MaxEraStakeValues - 1) AND stakes.last_element().era < current_era {
     raise error TooManyEraStakeValues;
}
```

**To Reproduce**
1. Fill up the `stakes` vec for a staker by calling `bond_and_stake` each time era changes
2. Make SURE you don't claim since that will clear the vec

**Expected behavior**
Just print a message to the user that they should claim first since staker info limit has been reached.
Also preventing the user from calling `bond_and_stake` regardless is also a good idea since the call will fail with an error.

**Screenshots**
![Screenshot from 2022-03-17 11-14-37](https://user-images.githubusercontent.com/3002868/158792215-48a9e6a9-d695-4fa3-b05c-7325da0416b3.png)

**Comment by impelcrypto** [comment]
The issue has been resolved.
![image](https://user-images.githubusercontent.com/92044428/172840672-b7f7fff0-b516-4589-8e87-c1eb299e10e9.png)
