### ISSUE TITLE
astar portal is not recognizing polkadot.js extension on chrome

### ISSUE THREAD

**Issue by aydin33** [AstarNetwork/astar-apps#289]
Hello,

I want to connect my wallet to astar portal. Once i have rejected the permission request to my wallet from portal. But after that rejection, i couldnt have managed to connect the wallet to portal in no way, because whenever i click the connect button, a popup occurs saying to install polkadot.js extension.

Thanks in advance..

**Comment by hoonsubin** [comment]
![Screen Shot 2022-03-17 at 1 37 26 PM](https://user-images.githubusercontent.com/40356749/158810007-d068be85-22d7-4485-a20d-bb8375ce840e.png)
You can change the access permission by clicking the `Manage Website Access` and allow the portal to gain access to the extension.
