### ISSUE TITLE
[Feature suggestion]Vote Dapp for DAO

### ISSUE THREAD

**Issue by mccallum147** [AstarNetwork/astar-apps#290]
**Motivation**
> Describe the need or frustration that motivated you to make this suggestion.

I launched DAO AstarBots2.0 yesterday, but domain .eth is required to use snapshot, and the gas cost is high. 

https://snapshot.org/

**Suggested Solution**
> Describe your suggested solution to the need or frustration that you are experiencing.

Making DApp that can vote on the Astar Network with domain .astr would be great for projects starting DAO in the future.

**Additional Information**
> Provide any additional information that you believe may help us evaluate your suggestion.

Self-introduction.
AstarBots has abandoned the continuation of the project by the operator.
Therefore, some people in the Japanese room started a regeneration project AstarBots2.0. The first goal is to publish an NFT of AstarBots 3D data and distribute it to AstarBots owners for free. And we will make it possible to go to the Metaverse world with the 3D data. The ultimate goal is to create an independent virtual nation.

Thank you.

AstarBots2.0
discord
https://discord.gg/6xyRkUFw

**Comment by Kahonnohak** [comment]
Thanks, and sorry for the slow reply. Integration with Snapshot is not planned and we will update once our DAO governance model is ready to share.
