### ISSUE TITLE
Claimed amount is 0 after claiming

### ISSUE THREAD

**Issue by Vert2785** [AstarNetwork/astar-apps#30]
I Pressed Claim button for PolkaEx app, transaction was successful. But claimed amount is shown 0. 

![image](https://user-images.githubusercontent.com/90528391/136209195-471a1ce7-5fb7-4e45-8e4a-797f896653a1.png)

I tried to Claim second time, but got error:

![image](https://user-images.githubusercontent.com/90528391/136209135-0d95c561-dd2c-4396-8a29-bd66fde4300d.png)

**Comment by Vert2785** [comment]
Also how to check if there is any Stake or Claim transactions? I can't see anything on subscan:
https://shibuya.subscan.io/account/XSUR8EwUrgm7ammqb4PFACB55k8ZpzEPbKwm3kyUSYdyCkF?tab=extrinsic

**Comment by impelcrypto** [comment]
This issue has been resolved.
