### ISSUE TITLE
Recommendation Inputs for UI

### ISSUE THREAD

**Issue by marvelet** [AstarNetwork/astar-apps#34]
On Register dApp section, please add notes such as :
- square format
- max / min pixel
- file format, jpg, png, others

On Information Box :
- Kindly add header About, Contract Address and Website Link in info box, and several lines also good (see picture
![rec test](https://user-images.githubusercontent.com/87793956/136223533-9f198979-0007-4e71-8dbc-9848f7ccf59b.jpg)
 attch)

**Comment by impelcrypto** [comment]
This issue has been resolved.
![image](https://user-images.githubusercontent.com/92044428/166179166-8a91b7d4-e89d-4179-9910-556a51109694.png)
