### ISSUE TITLE
Not able to connect to Astar Portal using SubWallet if both Polkadot JS and SubWallet installed in my browser

### ISSUE THREAD

**Issue by RyanDinh8** [AstarNetwork/astar-apps#360]
**Describe the bug**
This has been happening for the last few weeks. I was not able to connect to Astar Portal via SubWallet if if have both Polkadot JS and SubWallet installed.

**To Reproduce**
Please see the video:
https://drive.google.com/file/d/1gVpSHnMBILYXqQ3UfqE5OBKoSUJNnDvu/view?usp=sharing

**Expected behavior**
I can choose whichever wallet I want to connect to the portal.

**Desktop (please complete the following information)**
 - Device: Macbook pro 2016
 - Browser: Brave and Chrome
 - SubWallet extension version [0.3.3]

**Additional information**
Please fix it soon. Thanks.

**Comment by impelcrypto** [comment]
Hi @RyanDinh8 
I checked but cannot reproduce on my end (Mac, Chrome).

Demo:
https://user-images.githubusercontent.com/92044428/163774102-1326e9be-a2dc-4044-9192-b8671c00bea1.mov

Could you update your chrome and check the 'Manage Website Access' configuration?
![image](https://user-images.githubusercontent.com/92044428/163774236-38b70d44-fd2f-4abf-95d5-1f117a172789.png)

**Comment by RyanDinh8** [comment]
Hi @impelcrypto,

Just updated both Chrome and Brave, and it worked now. Thanks a lot.

Ryan.

**Comment by RyanDinh8** [comment]
Hi there,

It happens again. Please check it. 

[https://drive.google.com/file/d/1sKA3rLWNMwZPkouCu3IbiFxC1ejxLVmD/view?usp=sharing](url)

**Comment by impelcrypto** [comment]
Hi @RyanDinh8 
Thank you for your report. Could you take a look at [this](https://astar-apps--pr386-fix-wallet-firefox-gd7um6a7.web.app/) staging URL, pleas?

**Comment by RyanDinh8** [comment]
Hi @impelcrypto 

Just checked it. I think it still happens on the staging URL. 

Device: MacBook Pro
Browser: Chrome: Version 100.0.4896.127 (Official Build) (x86_64)
SubWallet: 0.3.6

[https://www.loom.com/share/972c58cead9c46f1af648e880983c628](url)

**Comment by impelcrypto** [comment]
Hi @RyanDinh8 
I have resolved the issue in [this](https://github.com/AstarNetwork/astar-apps/pull/434) PR. Please take a look at [this](https://astar-apps--pr434-fix-accountmap-0dr000yl.web.app/#/assets) staging URL.

**Comment by RyanDinh8** [comment]
Hi @impelcrypto, Thank you very much, it works well now.

**Comment by hieudd** [comment]
Hi @impelcrypto pls check, still can't connect the first time: https://www.loom.com/share/c8d5397b5ad946bb8a34ef60fd5235d8
