### ISSUE TITLE
Staked but there is still Transferable amount

### ISSUE THREAD

**Issue by pnpdude** [AstarNetwork/astar-apps#37]
![image](https://user-images.githubusercontent.com/90048622/136249613-5b25f23c-0c19-4b23-bc8c-ecd713c122d3.png)

Try testing sending to another account
![image](https://user-images.githubusercontent.com/90048622/136249897-844316ca-5a8e-4a72-bdeb-728a925a17eb.png)

And Dark mode automatically turns on, can't turn on light mode

**Comment by pnpdude** [comment]
Plus, we will need to have staking period, unstaking period, and APY.

**Comment by impelcrypto** [comment]
This issue has been resolved.
