### ISSUE TITLE
[Bug report] Wallet connection is not being recognized after switching between networks

### ISSUE THREAD

**Issue by hoonsubin** [AstarNetwork/astar-apps#380]
**Describe the bug**
> A clear and concise description of what the bug is.

After testing https://github.com/AstarNetwork/astar-apps/pull/377 in the staging environment, my Talisman wallet connection is not being shown even though the page can read my account.

**To Reproduce**

1. Open the portal page
2. Switch the networks
3. After some point, the wallet connection disappears

**Expected behavior**
> A clear and concise description of what you expected to happen.

The wallet connection should always be established.
Furthermore, when you enter the portal page for the first time with a polkadot wallet, the page will ask for you to allow the page to access the wallet before the user even presses connect. This should not be the case and the page should only request access to the extension when the user clicks connect.

**Screenshots**
> If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/40356749/166420597-97fad163-bfd8-4e6f-b161-1cbe7270f0a1.mp4

**Desktop (please complete the following information)**
 - OS: Windows
 - Browser: Chrome
 - Version: Latest
 - Wallet: Talisman

**Smartphone (please complete the following information)**

**Additional information**
> Add any other information about the problem here.

There were no console error logs

**Comment by sirius651** [comment]
Just sharing status, it seems not quite simple to resolve this. `web3enable` function, which is requested authorization for first user is called automatically. to detect metadata or call `web3Accounts`, that function must be executed first. so I should refactor as calling to related all function once user trying to connect. let me check more deeper
