### ISSUE TITLE
Claimed in this Era error prevention

### ISSUE THREAD

**Issue by Vert2785** [AstarNetwork/astar-apps#39]
It would be good to see somewhere on Claim popup window that claim already happened this Era.
![image](https://user-images.githubusercontent.com/90528391/136256249-0386ee8c-0459-4d2f-9222-f25b21606bf0.png)

Because currently I can claim, but after that i got error:
![image](https://user-images.githubusercontent.com/90528391/136255984-454dbcc0-7c10-40b5-8da0-96a203b26baf.png)

**Comment by impelcrypto** [comment]
I'm closing this issue since the claiming method has been changed.
Ref: https://forum.astar.network/t/individual-claim-on-shiden/2914
