### ISSUE TITLE
Unused unstake button displayed and Units of measurement confuse the user

### ISSUE THREAD

**Issue by Parker27** [AstarNetwork/astar-apps#40]
1. Please use only the SBY measurement, the kSBY or mSBY units are just confusing.

2. The UNSTAKE button, despite not having a stakin, is still displayed.

3. Show APY.

4. Use a different font size to see numbers as they are very small.

5. Use only two decimal places in numbers.

**Comment by impelcrypto** [comment]
This issue has been resolved.
