### ISSUE TITLE
Invalid injector error message

### ISSUE THREAD

**Issue by MadDog2022** [AstarNetwork/astar-apps#421]
Hello, i unstaked my ASTR and it unbonded in era 42. However now my TOTAL Balance says $0 even though I have 135,000 coins and when I click on Vesting / Unlock I click give "invalid injector" error. Why? Thx
<img width="1123" alt="Screen Shot 2022-05-28 at 6 47 54 AM" src="https://user-images.githubusercontent.com/98399188/170824251-815705e5-4d1a-45e5-9b26-1b881521a78f.png">

**Comment by Dinonard** [comment]
Hello, if unbonding period passed it means you can withdraw unbonded funds. They are not automatically unlocked for you.

**Comment by MadDog2022** [comment]
<img width="528" alt="Screen Shot 2022-05-28 at 8 48 59 AM" src="https://user-images.githubusercontent.com/98399188/170828313-be528df0-38c8-4447-9c8e-de19a7216141.png">

It says I have 135k unbonded funds but when i try to withdraw it says "invalid injector"

**Comment by MadDog2022** [comment]
<img width="297" alt="Screen Shot 2022-05-28 at 8 51 12 AM" src="https://user-images.githubusercontent.com/98399188/170828363-746338cf-c1e4-4ecb-a1b6-9934fb3f560d.png">

**Comment by MadDog2022** [comment]
so is it still unlocking, even though in next era, or are the unbonded?

**Comment by MadDog2022** [comment]
i fixed it somehow
