### ISSUE TITLE
Returns "Internal Server Error" when trying to connect to local node[Bug report]

### ISSUE THREAD

**Issue by masafumimori** [AstarNetwork/astar-apps#423]
**Describe the bug**
Switching network in Astar portal to local network while running local node leads to a crash in which console shows "internal server error" and browser shows spinner that never disappears.
For some reasons, when connecting to MetaMask, it loads the page fine although no details are shown.

**To Reproduce**
1. Go to '[Astar resease](https://github.com/AstarNetwork/Astar/releases)' and download "[astar-collator-3.29.0-macos-x86_64.tar.gz](https://github.com/AstarNetwork/Astar/releases/download/v3.29.0/astar-collator-3.29.0-macos-x86_64.tar.gz)"
2. Run local node by running command `./astar-collator --port 30333 --ws-port 9944 --rpc-port 9933 --rpc-cors all --alice --dev`
3. Access to [Astar portal](https://portal.astar.network/#/assets) and connect wallet (either Polkadot or Clover), then switch to Local network.

**Expected behavior**
Loads the page and shows info associated with the connected wallet.

**Screenshots**
![Screenshot 2022-05-30 at 11 34 55](https://user-images.githubusercontent.com/71799690/170907657-5e531dfd-301e-48ab-92a9-e10cc23d3f91.png)
![Screenshot 2022-05-30 at 11 35 05](https://user-images.githubusercontent.com/71799690/170907674-0d34b38d-6943-4e50-be7a-5e3a48916610.png)
![Screenshot 2022-05-30 at 11 48 23](https://user-images.githubusercontent.com/71799690/170908247-3b7627ab-c969-4c67-8a89-97a0880a8d5f.png)

**Desktop (please complete the following information)**
 - OS: macOS Monterey 12.0 (M1Pro)
 - Browser Brave v 1.39.111 and Chrome Version 102.0.5005.61

**Comment by impelcrypto** [comment]
Hi @masafumimori, thank you for your report. The issue has been resolved.
