### ISSUE TITLE
Switch from wallet in dApp store

### ISSUE THREAD

**Issue by fiexer** [AstarNetwork/astar-apps#48]
**Motivation**
If you use multiple accounts, you have to go first to your balance before seeing staking amount of that wallet.

**Suggested Solution**
Make it possible to easily switch from wallet in the dApp store page

**Alternatives**
/

**Additional Information**
/

**Comment by hoonsubin** [comment]
duplicate of https://github.com/PlasmNetwork/astar-apps/issues/29
