### ISSUE TITLE
Address display/select cross page

### ISSUE THREAD

**Issue by bLd75** [AstarNetwork/astar-apps#49]
Currently, the address selection/balance view is only available from the balance page.

It would be nice to have this box (including the balance) on every pages, on the top right for example.
Adding the verified identity would also be a useful extra.

![image](https://user-images.githubusercontent.com/18489502/136472923-f5272039-d71b-410b-913d-0aef0c0abe78.png)

**Comment by hoonsubin** [comment]
fixed with https://github.com/PlasmNetwork/astar-apps/pull/68 and https://github.com/PlasmNetwork/astar-apps/pull/63
