### ISSUE TITLE
[Bug report] The dots balance of the receiver/destination evm address when XCM Cross Chain transfer dosen't display and appears 0 when imput the reciver evm address on V2 portal 

### ISSUE THREAD

**Issue by dennisolarfdez** [AstarNetwork/astar-apps#512]
[Bug report] The dots balance of the reciver/destination evm address when XCM Cross Chain transfer dosen't display and appears 0 when imput the receiver evm address on V2 portal. This should load the current dot balance on the evm address. I have 101 dots and it displays 0. This issue can leads to mistakes while users transfers and confusion. 
![16631676161374555437163511846040](https://user-images.githubusercontent.com/95296065/190190995-e2e7c20e-039a-4916-a4f6-247532399b99.jpg)

**Comment by impelcrypto** [comment]
Hi @dennisolarfdez could you test it again at [this](https://astar-apps--pr510-feture-xcm-refactori-av9maqo9.web.app/) staging URL?

**Comment by impelcrypto** [comment]
Fixed in [this](https://github.com/AstarNetwork/astar-apps/pull/510) PR
