### ISSUE TITLE
yarn dev error

### ISSUE THREAD

**Issue by hqwangningbo** [AstarNetwork/astar-apps#616]
node version v18.12.1
yarn version 1.22.19
MacOS M1

1. yarn 
2. yarn dev

The error message is as follows

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/57781136/205144670-31d8431e-ea9e-4151-b473-a13a8d012f8b.png">

**Comment by impelcrypto** [comment]
The spec of my computer is the same as described above but I can't reproduce the error. How about you @gluneau ?

**Comment by hqwangningbo** [comment]
@impelcrypto @gluneau I don’t know what the problem is. I ran the yarn command without any error. Yarn dev would report an error. My colleague finished running the yarn command and sent me node_moudles, and I could run it successfully.
