### ISSUE TITLE
Can't switch metamask account after metamask is connected.

### ISSUE THREAD

**Issue by Vert2785** [AstarNetwork/astar-apps#64]
I can Connect to Metamask from Balance view:
![image](https://user-images.githubusercontent.com/90528391/136703629-8c78b04b-80d0-4a8e-8acd-2a0bddbb6932.png)

Once Metamask is connected I can't switch account in dapp portal anymore even I have more then one account in my Metamask:
![image](https://user-images.githubusercontent.com/90528391/136703696-188248fc-ca7f-4fdd-8494-32e7b1c07e6d.png)

But when I switched account in Metamask my address is not updated in dapp portal.
![image](https://user-images.githubusercontent.com/90528391/136704155-86ce83cc-8b29-4680-8820-de64f3696b83.png)

**Expected behavior**
Account selected in metamask always should match the account selected in dapp portal.

**Desktop (please complete the following information)**
 - Browser chrome
 - Version 94.0.4606.71

**Comment by impelcrypto** [comment]
This issue has been resolved.
https://gyazo.com/4dbaa84e03a0b3aca8d2a0e11a7291dc
