### ISSUE TITLE
Integrate Support on Astar Portal for Trust Wallet App now compatible with EVM Astar Network environment due Trust Wallet App recent custom EVM Adding feature upgrade 

### ISSUE THREAD

**Issue by dennisolarfdez** [AstarNetwork/astar-apps#641]
Trust Wallet App Today Announced that Integrates its new feature ( ADD a Custom EVM Network manually), is now possible to ADD Astar Network EVM to Trust Wallet APP manually, for mobile and PC. Trust Wallet is used by almost 60 million people worldwide with 10 million Monthly Active Users making it the largest mobile wallet in the world.14 Nov 2022

https://community.trustwallet.com/t/trust-wallet-adds-custom-network-support-for-the-mobile-app/643116

It is very important to integrate the support to connect Trust Wallet App to Astar Portal EVM when we click on connect wallet, it should appear together with metamask, talisman... in the same menu of available wallets to connect to the Astar Portal. 

Integrate in the Astar Portal same EVM Wallet availables list as metamask 

More details

https://community.trustwallet.com/t/how-to-add-a-custom-network-on-the-trust-wallet-mobile-app/626781

![20221224_040147](https://user-images.githubusercontent.com/95296065/209454874-ebc367e9-9b23-4373-b6ae-1a6413a5cbe2.jpg)

Thank you

**Comment by Usernamethoma** [comment]
@dennisolarfdez We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by Chukwulawrence** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/7KbQyuY5NoxyrhNz5

**Comment by impelcrypto** [comment]
Closing this issue as the latest version of Trust wallet doesn't have adding custom network feature.
