### ISSUE TITLE
Error for metamask address during staking

### ISSUE THREAD

**Issue by Vert2785** [AstarNetwork/astar-apps#65]
**Describe the bug**
I have selected my Metamask account on balance view:
![image](https://user-images.githubusercontent.com/90528391/136704281-0332140a-8c51-4cf0-9775-75fe82f95f06.png)

When I want to Stake, I choose my Metamask address from dropdown list on Stake popup window:
![image](https://user-images.githubusercontent.com/90528391/136704348-0f906c30-66c1-48ed-abf4-d75e5783dde6.png)

I got this error:
![image](https://user-images.githubusercontent.com/90528391/136704476-84d8d948-541e-4e15-b249-5b1fdcbf1357.png)

**Expected behavior**
All validations of wrong addresses should be on step where Metamask account is connected to portal, but not received after stake transaction is signed.

**Desktop (please complete the following information)**

 - Browser chrome
 - Version 94.0.4606.71

**Comment by impelcrypto** [comment]
I'm closing this issue since the portal doesn't support staking from the ECDSA account.
