### ISSUE TITLE
[Bug report] Clicking max may prevent you being able to dapp stake in production  

### ISSUE THREAD

**Issue by ltfschoen** [AstarNetwork/astar-apps#724]
**Describe the bug**

**To Reproduce**
1. Go to https://portal.astar.network/astar/dapp-staking/stake?dapp=0xa602d021da61ec4cc44dedbd4e3090a05c97a435 and stake all the ASTR tokens you have in an account into a dapp like the one at that link.
2. Click the "max" button in the UI 
i had a balance of for example 1,000.909000000000000001 ASTR.
in the UI it showed my "Transferable Balance" as 1.001K ASTR,
and in the input field section it showed "Balance: 1,001 ASTR"
and when i clicked the "max" button in the UI, it populated the input field with 991 ASTR
3. See error:
then it displayed the warning:
```
Account must hold greater than 10ASTR in transferrable when you stake.
```
and displayed error:
```
The amount of token to be staking must be greater than 500 ASTR.
```
even though i was trying to stake with a value greater than 500 ASTR
4. Try without encountering error:
so when i didn't use the "max" button and instead just manually entered 991 ASTR, it showed the same error.
but when i entered 990 ASTR the error disappeared.

So it seems to be setting aside the 10 ASTR, by doing 1000.9 - 10 = 990.9, but then rounding up to the nearest integer of 991 instead of rounding down to 990. 

It appears to be related to this code
https://github.com/AstarNetwork/astar-apps/blob/main/src/components/dapp-staking/stake-manage/StakeForm.vue#L177

That happened yesterday.  I ended up staking manually with a lesser amount due to the bug.

Today I tried to replicate it locally in development by cloning commit f45d64e11a65e186115c60cb8ffcae935188a23f, which doesn't appear to have been pushed to production yet.

I just hard-coded a value like '1000909000000000000001' here https://github.com/AstarNetwork/astar-apps/blob/main/src/hooks/dapps-staking/useStake.ts#L42 to represent '1000.909000000000000001', and so now:

in the UI it showed my "Transferable Balance" as 1.001K ASTR,
and in the input field section it showed "Balance: 1,000.909 ASTR"
and when i clicked the "max" button in the UI, it populated the input field with 990.909 ASTR

Similar to other issue https://github.com/AstarNetwork/astar-apps/issues/176

**Expected behavior**
> A clear and concise description of what you expected to happen.

I expect production to allow me to stake my full balance and automatically leave aside minimum amounts that need to remain transferrable. Note that it appears it has been resolved with that hotfix, although I'd prefer that it allowed advanced users to toggle so it shows the full 18 decimal places that are going to be staked, so advanced users know that their "max" balance is being staked, and not a fractional amount being left behind due to rounding in the UI.

**Screenshots**
> If applicable, add screenshots to help explain your problem.

<img width="339" alt="Screen Shot 2023-03-30 at 12 44 04 pm" src="https://user-images.githubusercontent.com/6226175/228709252-4c9db0b1-8d58-4109-af0b-237acd697b30.png">

**Desktop (please complete the following information)**
 - OS: macOS
 - Browser Brave
 - Version 1.48.164

**Comment by impelcrypto** [comment]
Hi @ltfschoen,
Thank you for your report. Yes, we are fixing this issue right now. Could you help test it again at this staging URL? https://staging.portal.astar.network/

**Comment by ltfschoen** [comment]
> Hi @ltfschoen, Thank you for your report. Yes, we are fixing this issue right now. Could you help test it again at this staging URL? https://staging.portal.astar.network/

yes, i tried staking the using the staging URL and it works fine now, thanks!
