### ISSUE TITLE
Add network status indication

### ISSUE THREAD

**Issue by bobo-k2** [AstarNetwork/astar-apps#74]
**Motivation**
Portal users don't have information about network status and can't know if their transaction will pass or not.

**Suggested Solution**
Add the current block time under the network status bar and mark it red if the block time is more than 10 times the average

**Comment by sirius651** [comment]
what would be average of block time generally?

**Comment by bobo-kovacevic** [comment]
> what would be average of block time generally?

I am also unsure, @hoonsubin  mentioned it in one conversation and I put it to the ticket. Sounds to me like we need to subscribe for new blocks and calculate average time between blocks

**Comment by hoonsubin** [comment]
The average block time can be found here https://github.com/PlasmNetwork/Astar/blob/6573df42d5aa5af8b51e35c1b09fbaa5392f4f97/runtime/shibuya/src/lib.rs#L62
The minimum block time can be queried via `api.const.timestamp.minimumPeriod`
![Screen Shot 2021-11-17 at 9 37 49 AM](https://user-images.githubusercontent.com/40356749/142165808-daca91dc-00a0-428c-be68-fed70a48fdd4.png)

**Comment by impelcrypto** [comment]
Hi @bobo-k2 

Is this issue still status as 'Open'? By the way, this is the code to calculate average block time.

https://github.com/AstarNetwork/astar-apps/blob/main/src/hooks/chain/useAvgBlockTime.ts#L109

**Comment by bobo-k2** [comment]
Closing as fixed
