### ISSUE TITLE
[Bug report] Question for "The maximum number of eras you can claim at once is 50." message.

### ISSUE THREAD

**Issue by johnnyji-dev** [AstarNetwork/astar-apps#742]
I tried to claim eras on portal.
And I have seen "The maximum number of eras you can claim at once is 50." message before I claimed.
My unclaimed eras was 55. So I expected that when I claim, the remaining eras will be 5.

But my claiming transaction result shows that 55 eras all claimed.
I think the claiming contract is not limited eras count at once or the message on portal about claim-info is wrong.
Anything-else case may be only wrong on shibuya testnet settings.

I attached my transaction link below.
https://shibuya.subscan.io/extrinsic/0xb5fe47ab7bdcbeb24a926558e2f562e931def5e250f38d128affdcf021e9d220

I am developing astar transfer and staking system on my service.
So I wanna get some information about claim definitly.

Thx~

**Comment by bobo-k2** [comment]
Hi @johnnyji-dev thank you for reporting the issue. I would say information about 50 eras that can be claimed at once is not correct. Number of eras claimed depends on claim transactions batch weigh, so it can be more on less than 50 transactions in a batch.

**Comment by johnnyji-dev** [comment]
> 

Oh really?! I misunderstood the meaning of message. Thx for your advice.

**Comment by bobo-k2** [comment]
The message is misguiding and I will fix it.
