### ISSUE TITLE
Polkadot js wallet connects but astar app stays busy (blue circle cycles no connection to app)

### ISSUE THREAD

**Issue by astarfan2023** [AstarNetwork/astar-apps#744]
I made a transaction to unlock vested astar tokens, paid gas fee for 30 seconds service, transaction never completed.  Seems my wallet is stuck waiting for this transaction, now cannot reconnect to app.  Polkadot js wallet connects to app but app does not load, stays busy - trying to complete last transaction?  Does anyone have any advice?

**Comment by impelcrypto** [comment]
Hi, could you try to connect to other endpoints and test it again?
