### ISSUE TITLE
[Bug report] "Your Stake" dApp numbers incorrect on portal.astar.network

### ISSUE THREAD

**Issue by jimwavefive** [AstarNetwork/astar-apps#77]
dApp staking shows incorrect numbers against dApp on https://portal.astar.network/#/store/discover-dapps after staking twice to same dApp.

**To Reproduce**
1. Using polkadot.js wallet extension
2. Stake 10kSDN against Community Rewards Program - https://shiden.subscan.io/extrinsic/499376-3
3. Observe correct number against "Your stake" (10kSDN)
4. Make an additional stake of 90kSDN against same dApp - https://shiden.subscan.io/extrinsic/499461-3
5. Observe incorrect number against "Your stake":
![image](https://user-images.githubusercontent.com/59484786/137173699-ff4c7779-01d8-4b27-9bc1-09713ecdfaa5.png)

**Expected behavior**
"Your stake" should be 10k+90kSDN = 100kSDN. What it's actually showing is 27.9999 kSDN which also happens to be the remaining balance of SDN in my account i.e. SDN that I have not yet staked.

**Desktop (please complete the following information)**
 - OS: Windows 10
 - Browser Brave
 - Version 1.30.89 Chromium: 94.0.4606.81 (Official Build) (64-bit)

**Comment by cryptovestor21** [comment]
some mistakes on my end - can be ignored
