### ISSUE TITLE
[Bug report] Claim Dapp - Call vector exceeds limit error on Ledger nano S

### ISSUE THREAD

**Issue by MateuszMielniczuk** [AstarNetwork/astar-apps#804]
**Description**

I am using Ledger nano S device connected to polkadot.js chrome extension. I can see information that there can be claimed only 2 eras with this device. Having more than 2 (currently over 20 eras to claim) when I am clicking on Claim button in dApp Staking panel and then Sign on Ledger I am getting error: ` Call vector exceeds limit.` so it is not possible to claim any rewards.

I've opened similar issue on Zondax profile: https://github.com/Zondax/ledger-astar/issues/20 and had response from developer that: " It should be something that Astar Dapp should handle, and only send 2 call at a time." 

**Steps to Reproduce**

1. Go to https://portal.astar.network/astar/dapp-staking/discover
2. Click on 'Claim' button on `My Rewards` tab
3. Sign on transaction on polkadot.js extension popup

**Expected vs. Actual Behavior**

Knowing Ledger device limitations expected behavior would be to claim 2 eras rewards.

**Environment**

- Latest Brave browser on Ubuntu 22.04
- Latest Zondax Astar app on Ledger device: 2.25.2 (tested with Astar and Astar XL apps)
- Ledger nano S device

**Comment by MateuszMielniczuk** [comment]
Problem solved, it turns out there is a wallet icon on top of the dApp staking page. Before claiming reward I had  to turn on option:
`This is a Ledger account, connected and running Astar app` and sign by Ledger.
Then claiming reward is working on both Astar and Astar XL ledger apps.

**Comment by Health15** [comment]
> Problem solved, it turns out there is a wallet icon on top of the dApp staking page. Before claiming reward I had to turn on option: `This is a Ledger account, connected and running Astar app` and sign by Ledger. Then claiming reward is working on both Astar and Astar XL ledger apps.

Its not help me

**Comment by impelcrypto** [comment]
Hi @Health15 
I've just tried and it works on my end.
You might want to check conditions below: 
* your Astar ledger app is up to the latest version (2.57.0)  
* the toggle in 'This is a Ledger account, connected and running Astar app' is turned on
* use with Polkadot.js wallet

![Screenshot 2024-01-09 at 5 36 56 PM](https://github.com/AstarNetwork/astar-apps/assets/92044428/129bb00f-7802-4c7c-a3c4-e8d230fe5db5)

**Comment by MateuszMielniczuk** [comment]
> > Problem solved, it turns out there is a wallet icon on top of the dApp staking page. Before claiming reward I had to turn on option: `This is a Ledger account, connected and running Astar app` and sign by Ledger. Then claiming reward is working on both Astar and Astar XL ledger apps.
> 
> Its not help me

For me it also not always working lately. After some time I have to clear my browser cache or click `?` help icon on Astar Portal and  click `Clear the Local Storage` button.
