### ISSUE TITLE
[Feature suggestion] Users can see the dapps store page when they connect to custom network.

### ISSUE THREAD

**Issue by y-shijo** [AstarNetwork/astar-apps#98]
**Motivation**
Currently, users cannot see the dapps store page when they connect to custom network. As of now, sometimes Shiden network is unstable so users want to switch to the other RPC endpoint via custom network option. But in this case, users cannot see the dapps stores, so that they cannot stake their token on registered dapps.

**Suggested Solution**
using `rpc.system.chain()` as keys to fetch the registered dapps from firebase.

**Comment by impelcrypto** [comment]
The issue has been resolved.
![image](https://user-images.githubusercontent.com/92044428/166177121-ac44cab1-5822-4925-b04b-33f3900c5fab.png)
